charges.json
TXNRP/tx-policies pull request #3
Opened 2023-10-31 20:14 UTC by GreenyMCR

2023-10-31 20:19 UTC, Ehbw approved these changes
Manually corrected the format here, I recommend using a tool such as [jsonlint](https://jsonlint.com/) to validate and format your changes.

2023-11-01 20:05 UTC, Ehbw requested changes

2023-11-01 20:05 UTC, Ehbw commented on charges.json
> +        "title": "Recklless Driving",
```suggestion
        "title": "Reckless Driving",
```

2023-11-01 20:05 UTC, Ehbw commented on charges.json
> +        "jailtime": ,
Needs an jailtime or 0

2023-11-01 20:05 UTC, Ehbw commented on charges.json
> +        "details": "No driver shall drink any alcoholic beverage while ina  vehicle upon a highway or roadway",
```suggestion
        "details": "No driver shall drink any alcoholic beverage while in a vehicle upon a highway or roadway",
```

2023-11-01 20:14 UTC, GreenyMCR commented
Updated

2023-11-03 23:23 UTC, Ehbw commented on charges.json
> +]
duplicate closing bracket
```suggestion

```

2023-11-04 19:07 UTC, Ehbw commented
Just realised something, I never mentioned how the new jailtime works, every month is a minute, so a charge with 600 set as jailtime would be 600 irl minutes (reduced by doing tasks within prison), so you may want to re-do some of the jailtime, though its up to you.

2023-11-14 17:08 UTC, merged